import { Model } from 'mongoose';

const SEED_VIDEOS = [
  {
    title: 'أساسيات تصميم الجسور — تحليل الإجهاد والضغط',
    description: 'شرح شامل لمبادئ تصميم الجسور الحديثة مع تطبيقات عملية على أنواع مختلفة من الجسور.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/bridge/640/360',
    category: 'civil',
    level: 'intermediate',
    tags: ['جسور', 'إجهاد', 'تصميم إنشائي'],
    duration: 3840,
    views: 48200,
    likes: 3100,
    instructorId: 'seed',
  },
  {
    title: 'دوائر التيار المتردد — من الصفر للاحتراف',
    description: 'درس متكامل يغطي تحليل دوائر AC وتطبيقاتها الصناعية في الحياة العملية.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/circuit/640/360',
    category: 'electrical',
    level: 'beginner',
    tags: ['AC', 'دوائر', 'كهرباء صناعية'],
    duration: 5220,
    views: 91000,
    likes: 6800,
    instructorId: 'seed',
  },
  {
    title: 'ديناميكيات الموائع — نظرية برنولي وتطبيقاتها',
    description: 'فهم عميق لحركة السوائل وتطبيقاتها في الأنابيب والطائرات والمحركات.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/fluid/640/360',
    category: 'mechanical',
    level: 'advanced',
    tags: ['برنولي', 'موائع', 'ايروديناميكا'],
    duration: 4500,
    views: 33500,
    likes: 2200,
    instructorId: 'seed',
  },
  {
    title: 'Clean Architecture في تطوير البرمجيات',
    description: 'كيف تبني مشاريع برمجية قابلة للصيانة والتوسع باستخدام مبادئ النظافة.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/code/640/360',
    category: 'software',
    level: 'intermediate',
    tags: ['معمارية', 'Clean Code', 'تصميم'],
    duration: 6300,
    views: 125000,
    likes: 9400,
    instructorId: 'seed',
  },
  {
    title: 'تصميم محركات الصواريخ — المبادئ الأساسية',
    description: 'مقدمة للدفع الصاروخي وتصميم غرف الاحتراق للمحركات الفضائية.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/rocket/640/360',
    category: 'aerospace',
    level: 'advanced',
    tags: ['صواريخ', 'دفع', 'فضاء'],
    duration: 7200,
    views: 19800,
    likes: 1650,
    instructorId: 'seed',
  },
  {
    title: 'انتقال الحرارة — الحمل والإشعاع والتوصيل',
    description: 'دراسة شاملة لآليات نقل الحرارة الثلاثة مع أمثلة صناعية تطبيقية.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://picsum.photos/seed/heat/640/360',
    category: 'chemical',
    level: 'intermediate',
    tags: ['حرارة', 'حمل حراري', 'إشعاع'],
    duration: 4800,
    views: 27300,
    likes: 1900,
    instructorId: 'seed',
  },
];

export async function seedDatabase(videoModel: Model<any>): Promise<void> {
  // كود لتفريغ قاعدة البيانات بناءً على طلبك للتخلص من الفيديوهات الوهمية
  await videoModel.deleteMany({});
  console.log('🗑️ تم تنظيف قاعدة البيانات بالكامل من الفيديوهات الوهمية');
}